# Generated by Django 2.2.1 on 2019-05-21 08:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_addspot_perfect_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addspot',
            name='category',
            field=models.CharField(blank=True, choices=[('FOOD', 'Food'), ('COCKTAILS', 'Cocktails'), ('WINE', 'Wine'), ('BEER', 'Beer'), ('COFFEE', 'Coffee'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addspot',
            name='perfect_for',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Quick', 'Something quick'), ('Last_min', 'Last-minute plans'), ('Impress', 'Impressing guests'), ('Date', 'Date night'), ('Group', 'Big group'), ('Cozy', 'Cozy vibe'), ('Expensive', "Treat yo' self"), ('Outdoor', 'Sunny day')], max_length=56, null=True),
        ),
    ]
