# Generated by Django 2.2.1 on 2019-05-24 07:31

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20190523_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='addspot',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='addspot',
            name='location',
            field=models.CharField(blank=True, choices=[('East Village', 'East Village'), ('West Village', 'West Village'), ('Williamsburg', 'Williamsburg')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addspot',
            name='perfect_for',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Something quick', 'Something quick'), ('Last-min plans', 'Last-min plans'), ('Impressing guests', 'Impressing guests'), ('Date night', 'Date night'), ('Big group', 'Big group'), ('Peace & quiet', 'Peace & quiet'), ('Living large', 'Living large'), ('Sunny days', 'Sunny days')], max_length=107, null=True),
        ),
    ]
