# Generated by Django 2.2.1 on 2019-05-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20190524_0331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddSpot',
        ),
    ]
