# Generated by Django 2.2.1 on 2019-05-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_addspot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addspot',
            name='id',
        ),
        migrations.AlterField(
            model_name='addspot',
            name='name',
            field=models.CharField(default='New', max_length=30, primary_key=True, serialize=False),
        ),
    ]
