# Generated by Django 2.2.1 on 2019-05-24 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20190524_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.AddSpot')),
            ],
        ),
    ]
