# Generated by Django 2.2.1 on 2019-06-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_testentrymodel_teststoremodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotlocation',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
