# Generated by Django 2.2.1 on 2019-06-08 11:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0022_reviewrecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddSpot',
            new_name='AddReview',
        ),
    ]
