# Generated by Django 2.2.1 on 2019-06-08 12:13

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20190608_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrecord',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewrecord',
            name='perfect_for',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Something quick', 'Something quick'), ('Last-min plans', 'Last-min plans'), ('Impressing guests', 'Impressing guests'), ('Date night', 'Date night'), ('Big group', 'Big group'), ('Peace & quiet', 'Peace & quiet'), ('Living large', 'Living large'), ('Sunny days', 'Sunny days')], max_length=107, null=True),
        ),
        migrations.AddField(
            model_name='reviewrecord',
            name='spotpic',
            field=models.FileField(blank=True, null=True, upload_to='spotpictures'),
        ),
    ]
