# Generated by Django 2.2.1 on 2019-06-17 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20190608_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlelocation',
            name='averating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='addreview',
            name='location',
            field=models.CharField(blank=True, choices=[('Alphabet City', 'Alphabet City'), ('Astoria', 'Astoria'), ('Battery Park', 'Battery Park'), ('Bed-Stuy', 'Bed-Stuy'), ('Cobble Hill', 'Cobble Hill'), ('DUMBO', 'DUMBO'), ('East Village', 'East Village'), ('Financial District', 'Financial District'), ('Fort Greene', 'Fort Greene'), ('Lower East Side', 'Lower East Side'), ('NoHo', 'NoHo'), ('SoHo', 'SoHo'), ('Times Square', 'Times Square'), ('Theater District', 'Theater District'), ('Tribeca', 'Tribeca'), ('Upper East Side', 'Upper East Side'), ('West Village', 'West Village'), ('Williamsburg', 'Williamsburg')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reviewrecord',
            name='location',
            field=models.CharField(blank=True, choices=[('Alphabet City', 'Alphabet City'), ('Astoria', 'Astoria'), ('Battery Park', 'Battery Park'), ('Bed-Stuy', 'Bed-Stuy'), ('Cobble Hill', 'Cobble Hill'), ('DUMBO', 'DUMBO'), ('East Village', 'East Village'), ('Financial District', 'Financial District'), ('Fort Greene', 'Fort Greene'), ('Lower East Side', 'Lower East Side'), ('NoHo', 'NoHo'), ('SoHo', 'SoHo'), ('Times Square', 'Times Square'), ('Theater District', 'Theater District'), ('Tribeca', 'Tribeca'), ('Upper East Side', 'Upper East Side'), ('West Village', 'West Village'), ('Williamsburg', 'Williamsburg')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='singlelocation',
            name='location',
            field=models.CharField(blank=True, choices=[('Alphabet City', 'Alphabet City'), ('Astoria', 'Astoria'), ('Battery Park', 'Battery Park'), ('Bed-Stuy', 'Bed-Stuy'), ('Cobble Hill', 'Cobble Hill'), ('DUMBO', 'DUMBO'), ('East Village', 'East Village'), ('Financial District', 'Financial District'), ('Fort Greene', 'Fort Greene'), ('Lower East Side', 'Lower East Side'), ('NoHo', 'NoHo'), ('SoHo', 'SoHo'), ('Times Square', 'Times Square'), ('Theater District', 'Theater District'), ('Tribeca', 'Tribeca'), ('Upper East Side', 'Upper East Side'), ('West Village', 'West Village'), ('Williamsburg', 'Williamsburg')], max_length=30, null=True),
        ),
    ]
