# Generated by Django 2.2.1 on 2019-06-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20190617_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlelocation',
            name='countrating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
