# Generated by Django 2.2.1 on 2019-06-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_singlelocation_countrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlelocation',
            name='load_image',
            field=models.FileField(blank=True, null=True, upload_to='spotpictures'),
        ),
    ]
