# Generated by Django 2.2.1 on 2019-06-19 00:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_singlelocation_load_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlelocation',
            name='perfect_for',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Something quick', 'Something quick'), ('Last-min plans', 'Last-min plans'), ('Impressing guests', 'Impressing guests'), ('Date night', 'Date night'), ('Big group', 'Big group'), ('Peace & quiet', 'Peace & quiet'), ('Living large', 'Living large'), ('Sunny days', 'Sunny days')], max_length=107, null=True),
        ),
    ]
