# Generated by Django 2.2.1 on 2019-06-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_singlelocation_perfect_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='high_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
