# Generated by Django 2.2.1 on 2019-06-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_profile_high_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_rating',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='high_rating',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
