# Generated by Django 2.2.1 on 2019-07-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_auto_20190707_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreview',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'Type'), ('FOOD', 'Food'), ('COCKTAILS', 'Cocktails'), ('WINE', 'Wine'), ('BEER', 'Beer'), ('COFFEE', 'Coffee'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='masteraddmodel',
            name='rating',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reviewrecord',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'Type'), ('FOOD', 'Food'), ('COCKTAILS', 'Cocktails'), ('WINE', 'Wine'), ('BEER', 'Beer'), ('COFFEE', 'Coffee'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='singlelocation',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'Type'), ('FOOD', 'Food'), ('COCKTAILS', 'Cocktails'), ('WINE', 'Wine'), ('BEER', 'Beer'), ('COFFEE', 'Coffee'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
    ]
