# Generated by Django 2.2.1 on 2019-07-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_cleanreviewmodel_singlelocationrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanreviewmodel',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
