# Generated by Django 2.2.1 on 2019-07-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_auto_20190719_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteraddmodel',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
