# Generated by Django 2.2.1 on 2019-07-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_auto_20190719_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleanreviewmodel',
            old_name='ave_rating',
            new_name='ave_ratings',
        ),
        migrations.RenameField(
            model_name='singlelocationrecord',
            old_name='ave_rating',
            new_name='ave_ratings',
        ),
        migrations.RenameField(
            model_name='singlelocationrecord',
            old_name='count_rating',
            new_name='count_ratings',
        ),
        migrations.AlterField(
            model_name='cleanreviewmodel',
            name='rating',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='masteraddmodel',
            name='rating',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
