# Generated by Django 2.2.1 on 2019-07-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_auto_20190719_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleanreviewmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='SingleLocationRecord',
        ),
        migrations.DeleteModel(
            name='CleanReviewModel',
        ),
    ]
