# Generated by Django 2.2.1 on 2019-07-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_cleanreviewmodel_singlelocationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkCreateNewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=30, null=True)),
                ('drinks', models.IntegerField(blank=True, null=True)),
                ('waters', models.IntegerField(blank=True, null=True)),
                ('maxBAC', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrinkCreateNewModelDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=30, null=True)),
                ('drinks', models.IntegerField(blank=True, null=True)),
                ('waters', models.IntegerField(blank=True, null=True)),
                ('maxBAC', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrinkCreateNewModelFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=30, null=True)),
                ('drinks', models.IntegerField(blank=True, null=True)),
                ('waters', models.IntegerField(blank=True, null=True)),
                ('maxBAC', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('highBAC', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
