# Generated by Django 2.2.1 on 2019-09-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_drinkcreatenewmodel_drinkcreatenewmodeldetails_drinkcreatenewmodelfinal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='home_city',
        ),
    ]
