# Generated by Django 2.2.1 on 2019-09-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_auto_20190909_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='home_city',
            new_name='homecity',
        ),
    ]
