# Generated by Django 2.2.1 on 2019-12-15 07:45

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_auto_20190909_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addreview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviewrecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='SingleLocation',
        ),
        migrations.RenameField(
            model_name='cleanreviewmodel',
            old_name='ave_ratings',
            new_name='ave_rating',
        ),
        migrations.AddField(
            model_name='cleanreviewmodel',
            name='count_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singlelocationrecord',
            name='count_wishlist',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cleanreviewmodel',
            name='perfect_for',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Great breakfast', 'Great breakfast'), ('On-the-run', 'On-the-run'), ('Last-min dinner', 'Last-min dinner'), ('Impressing guests', 'Impressing guests'), ('Date night', 'Date night'), ('Big group', 'Big group'), ('Peace & quiet', 'Peace & quiet'), ('Living large', 'Living large'), ('Sunny days', 'Sunny days')], max_length=119, null=True),
        ),
        migrations.AlterField(
            model_name='masteraddmodel',
            name='perfect_for',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Great breakfast', 'Great breakfast'), ('On-the-run', 'On-the-run'), ('Last-min dinner', 'Last-min dinner'), ('Impressing guests', 'Impressing guests'), ('Date night', 'Date night'), ('Big group', 'Big group'), ('Peace & quiet', 'Peace & quiet'), ('Living large', 'Living large'), ('Sunny days', 'Sunny days')], max_length=119, null=True),
        ),
        migrations.AlterField(
            model_name='singlelocationrecord',
            name='perfect_for',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Great breakfast', 'Great breakfast'), ('On-the-run', 'On-the-run'), ('Last-min dinner', 'Last-min dinner'), ('Impressing guests', 'Impressing guests'), ('Date night', 'Date night'), ('Big group', 'Big group'), ('Peace & quiet', 'Peace & quiet'), ('Living large', 'Living large'), ('Sunny days', 'Sunny days')], max_length=119, null=True),
        ),
        migrations.DeleteModel(
            name='AddReview',
        ),
        migrations.DeleteModel(
            name='ReviewRecord',
        ),
    ]
