# Generated by Django 2.2.1 on 2019-12-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thumbnail',
        ),
    ]
